# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/operator-framework/api
%global goipath         github.com/operator-framework/api
Version:                0.13.0

%gometa

%global common_description %{expand:
Contains the API definitions used by OLM and Marketplace.}

%global golicenses      LICENSE
%global godocs          README.md RELEASE.md hack/boilerplate.go.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        Contains the API definitions used by OLM and Marketplace

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/blang/semver)
BuildRequires:  golang(github.com/blang/semver/v4)
BuildRequires:  golang(github.com/google/cel-go/cel)
BuildRequires:  golang(github.com/google/cel-go/checker/decls)
BuildRequires:  golang(github.com/google/cel-go/common/types)
BuildRequires:  golang(github.com/google/cel-go/common/types/ref)
BuildRequires:  golang(github.com/google/cel-go/interpreter/functions)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(google.golang.org/genproto/googleapis/api/expr/v1alpha1)
BuildRequires:  golang(k8s.io/api/admissionregistration/v1)
BuildRequires:  golang(k8s.io/api/apps/v1)
BuildRequires:  golang(k8s.io/api/core/v1)
BuildRequires:  golang(k8s.io/api/policy/v1beta1)
BuildRequires:  golang(k8s.io/api/rbac/v1)
BuildRequires:  golang(k8s.io/api/scheduling/v1)
BuildRequires:  golang(k8s.io/apiextensions-apiserver/pkg/apis/apiextensions)
BuildRequires:  golang(k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install)
BuildRequires:  golang(k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1)
BuildRequires:  golang(k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1)
BuildRequires:  golang(k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation)
BuildRequires:  golang(k8s.io/apimachinery/pkg/apis/meta/v1)
BuildRequires:  golang(k8s.io/apimachinery/pkg/apis/meta/v1/unstructured)
BuildRequires:  golang(k8s.io/apimachinery/pkg/labels)
BuildRequires:  golang(k8s.io/apimachinery/pkg/runtime)
BuildRequires:  golang(k8s.io/apimachinery/pkg/runtime/schema)
BuildRequires:  golang(k8s.io/apimachinery/pkg/types)
BuildRequires:  golang(k8s.io/apimachinery/pkg/util/errors)
BuildRequires:  golang(k8s.io/apimachinery/pkg/util/intstr)
BuildRequires:  golang(k8s.io/apimachinery/pkg/util/runtime)
BuildRequires:  golang(k8s.io/apimachinery/pkg/util/validation)
BuildRequires:  golang(k8s.io/apimachinery/pkg/util/yaml)
BuildRequires:  golang(k8s.io/client-go/kubernetes/scheme)
BuildRequires:  golang(k8s.io/client-go/tools/record)
BuildRequires:  golang(k8s.io/client-go/tools/reference)
BuildRequires:  golang(sigs.k8s.io/controller-runtime/pkg/scheme)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/ghodss/yaml)
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md RELEASE.md hack/boilerplate.go.txt
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Feb 17 2022 Ish Shah <ishah@redhat.com> - 0.13.0-1%{?dist}
- Initial package
